[package]
name = "koenigsberg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "koenigsberg"
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.24", features = ["macros", "rt", "rt-multi-thread", "sync"] }
pyo3 = { version = "0.19", features = ["extension-module", "abi3", "abi3-py38"] }
datafusion = "32.0.0"
datafusion-common = { version = "32.0.0", features = ["pyarrow"] }
datafusion-expr = "32.0.0"
prost = "0.11"
prost-types = "0.11"
datafusion-optimizer = "32.0.0"
datafusion-sql = "32.0.0"
futures = "0.3"
