name: ci-test-examples

on:
  push:
    # Skip the backend suite if all changes are docs
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "**/*.qmd"
      - "*.md"
      - "codecov.yml"
      - ".envrc"
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["x86_64"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Rust latest
        run: rustup update

      # check how to use virtual environment https://stackoverflow.com/q/74668349/4001592
      - name: Create virtual environment
        run: python -m venv .venv

      - name: install dependencies
        run: |
          source .venv/bin/activate
          python -m pip install pytest maturin

      - name: develop
        run: |
          source .venv/bin/activate
          python -m maturin develop

      - name: pytest
        run: |
          source .venv/bin/activate
          python -m pytest --import-mode=importlib python/koenigsberg/tests/test_examples.py -v
        working-directory: ${{ github.workspace }}
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DATABASE: ibis_testing