name: ci-test-examples

on:
  push:
    # Skip the backend suite if all changes are docs
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "**/*.qmd"
      - "*.md"
      - "codecov.yml"
      - ".envrc"
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read


jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["x86_64"]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          command: 'develop'
          sccache: 'true'
          manylinux: auto

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: poetry pytest
        run: poetry run pytest --import-mode=importlib python/koenigsberg/tests/test_examples.py -v
        working-directory: ${{ github.workspace }}